import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Before;
import org.junit.Test;
import net.tutorial.utilities.TranslatorService;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by '135480' at '2/7/17 3:02 PM' with Gradle 3.1
 *
 * @author 135480, @date 2/7/17 3:02 PM
 */
public class LibraryTest {  
    @Test
    public void sampleShouldReturnTrue() {
        Library sample = new Library();
        assertTrue("Sample method should return 'true'", sample.sampleLibraryMethod());
    }
}
